feat: changed state passing from React context to Event Manager
Lomray-Software/react-modals pull request #3
Opened 2023-12-22 22:46 UTC by danial031193

2023-12-22 23:44 UTC, MatthewPattell requested changes

2023-12-22 23:44 UTC, MatthewPattell commented on README.md
>  const App = () => {
```
const App = () => (
  <>
    <Layout />
    <ModalRoot Modal={(props) => <Dialog {...props} />} />
  </>
)
```

2023-12-22 23:44 UTC, MatthewPattell commented on src/root.tsx
>   * ModalRoot Consumer
```suggestion
 * ModalRoot 
```

2023-12-22 23:44 UTC, MatthewPattell commented on src/types.ts
> +export type OmitStoreProps<T> = {
https://github.com/Lomray-Software/react-mobx-manager/blob/prod/src/with-stores.tsx#L16

2023-12-22 23:44 UTC, MatthewPattell commented on src/channel.ts
> +  HIDE = 'HIDE',
```suggestion
  OPEN = 'react-modals:open',
  HIDE = 'react-modals:hide',
```

2023-12-22 23:45 UTC, MatthewPattell commented
Support multimodal?

2023-12-24 09:49 UTC, danial031193 commented
> Support multimodal?

Yes

2023-12-24 15:48 UTC, MatthewPattell approved these changes

2023-12-24 22:17 UTC, merged